all:
	# If you wanted to build something first you'd put it in here.
	# You can just delete this file, or you can delete the ./run
	# file and have this file build a run binary.
	g++ -O3 -std=gnu++11 nbd.cpp -lgmp -o run

.PHONY: all
